name: CI

on:
  push:
    branches: master
    # schedule:
    #   - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: pip3 install -r requirements.txt
    - name: Fetch velib data
      run: ./script.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
